language: csharp
branches:
  only:
  - master
  - dev
solution: SaveLockscreenImage.sln
install:
  - nuget restore SaveLockscreenImage.sln
  - nuget install xunit.runner.console
script:
  - msbuild /p:Configuration=Release SaveLockscreenImage.sln
  - mono ./packages/xunit.runner.console.*/tools/net452/xunit.console.exe ./Test/bin/Release/Test.dll