image: Visual Studio 2017
install:
- set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin\amd64;%PATH%

version: 1.0.{build}
branches:
  only:
  - master
  - dev
# Do not build on tags (GitHub and BitBucket)
skip_tags: true
before_build:
- cmd: nuget restore
# Build Configuration, i.e. Debug, Release, etc.
configuration: Release
build:
  verbosity: minimal