version: 1.0.{build}
branches:
  only:
  - master
  - dev
# Do not build on tags (GitHub and BitBucket)
skip_tags: true
before_build:
- cmd: nuget restore
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
build:
  verbosity: minimal