version: 1.0.{build}
branches:
  only:
  - master
  - dev
# Do not build on tags (GitHub and BitBucket)
skip_tags: true
before_build:
- cmd: nuget restore
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
build:
  verbosity: minimal
test:
  # only assemblies to test
  assemblies:
    only:
      - \Test\bin\Release\Test.dll
# to run your custom scripts instead of automatic tests
test_script:
  - cmd: %xunit20%\xunit.console <assembly> -appveyor [options]

# to disable automatic tests
test: off