version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Make mono-xamarin.list
          command: echo "deb http://download.mono-project.com/repo/debian stretch main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
      - run:
          name: Get package list
          command: sudo apt-get update
      - run:
          name: Install Mono
          command: sudo apt-get install mono-complete
      - run:
          name: Download NuGet
          command: wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      - run:
          name: NuGet restore
          command: mono nuget.exe restore SaveLockscreenImage.sln
      - run:
          name: Build with MSBuild
          command: msbuild /p:Configuration=Release SaveLockscreenImage.sln
  #test:
#dependencies:
#  override:
#    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    #- echo "deb http://download.mono-project.com/repo/debian stretch main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
    #- sudo apt-get update
    #- sudo apt-get install mono-complete
    #- wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    #- mono nuget.exe restore SaveLockscreenImage.sln
#    - mono nuget.exe install xunit.runner.console
#    - msbuild /p:Configuration=Release SaveLockscreenImage.sln
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev