version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
dependencies:
  override:
#    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb http://download.mono-project.com/repo/debian stretch main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
    - sudo apt-get update
    - sudo apt-get install mono-complete
    - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - mono nuget.exe restore SaveLockscreenImage.sln
    - mono nuget.exe install xunit.runner.console
    - msbuild /p:Configuration=Release SaveLockscreenImage.sln