version: 2
jobs:
  build:
    docker:
      - image: mono:6
    steps:
      - checkout
      - run:
          name: NuGet restore
          command: nuget restore SaveLockscreenImage.sln
      - run:
          name: Build with MSBuild
          command: msbuild /p:Configuration=Release /verbosity:minimal SaveLockscreenImage.sln
  #test:
#dependencies:
#  override:
#    - mono nuget.exe install xunit.runner.console
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
      #- build
      #- test:
      #    requires:
      #      - build
          filters:
            branches:
              only:
                - master
                - dev